# Generated by Django 5.0.3 on 2024-03-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cost', models.PositiveIntegerField(default=0)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('min_users_group', models.PositiveIntegerField()),
                ('max_users_group', models.PositiveIntegerField()),
            ],
        ),
    ]
