# Generated by Django 5.0.3 on 2024-03-21 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusystem', '0004_productaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groups', to='edusystem.product')),
                ('user', models.ManyToManyField(related_name='groups_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
