# Generated by Django 5.0.3 on 2024-03-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusystem', '0005_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукт'},
        ),
        migrations.AlterModelOptions(
            name='productaccess',
            options={'verbose_name': 'Доступ к продукту', 'verbose_name_plural': 'Доступы к продуктам'},
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='link',
            field=models.URLField(verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_users_group',
            field=models.PositiveIntegerField(verbose_name='Максимальное кол-во пользователей в группе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_users_group',
            field=models.PositiveIntegerField(verbose_name='Минимальное кол-во пользователей в группе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_end',
            field=models.DateTimeField(verbose_name='Конец продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_start',
            field=models.DateTimeField(verbose_name='Старт продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='productaccess',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Валидноcть'),
        ),
    ]
