# Generated by Django 5.0.3 on 2024-03-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusystem', '0006_alter_group_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccess',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accesses', to='edusystem.product'),
        ),
    ]
