# Generated by Django 5.0.3 on 2024-03-22 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusystem', '0007_alter_productaccess_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lessons', to='edusystem.product'),
        ),
    ]
