# Generated by Django 5.0.3 on 2024-03-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusystem', '0008_alter_lesson_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='product',
            name='time_end',
            field=models.DateTimeField(blank=True, verbose_name='Конец продукта'),
        ),
    ]
