# Generated by Django 5.0.3 on 2024-03-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusystem', '0009_alter_user_options_alter_product_time_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец продукта'),
        ),
    ]
